# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jianjie.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(687, 633)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 661, 631))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(20, -30, 621, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(20, -130, 621, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(20, -10, 621, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setGeometry(QtCore.QRect(20, -50, 621, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_5 = QtWidgets.QLabel(self.page_5)
        self.label_5.setGeometry(QtCore.QRect(10, -20, 621, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page_5)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">永定河，古称治水、㶟水、桑干河、卢沟、浑河、无定河。是海河流域七大水系之一。流经内蒙古、山西、河北三省区、北京、天津两个直辖市、共43个县市，于屈家店与北运河汇合，部分洪水由北运河入海河，大部分洪水经永定新河于天津市滨海新区北塘镇入渤海。河流全长747公里，河道平均比降2.85‰。全流域面积4.7万平方公里 </span></p><p><span style=\" font-size:16pt; font-weight:600;\">永定河上游流经黄土高原，河水含沙量大，因此有“小黄河”“浑河”之称。下游河道因泥沙淤积，形成地上河，而且迁徙不定，故旧称“无定河”。1950～1960年代，先后在上游修建了册田、友谊、官厅三座大型水库（总库容29.66亿立方米），控制流域面积43402平方公里，下游设置了永定河泛区、三角淀以蓄洪滞洪，开挖永定新河入海河道，基本解决了洪涝问题。</span></p><p><span style=\" font-size:16pt; font-weight:600;\">1970年以后，由于气候及上游截流，官厅以下经常处于干涸状态，2019年始，开始实施生态补水，从山西省自黄河跨流域调水补充永定河水源。 [5-6]  2022年3月15日10时8分，位于永定河上游的山西大同册田水库开闸，出闸的清水向永定河下游流去。此次开闸放水，标志着永定河2022年春季生态补水全面启动。</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">北运河是流经北京市东郊和天津市的一条河流，为海河的支流。干流通州至天津也即京杭大运河的北段。古称白河、沾水和潞河。是起源于北京且唯一常年有水的河。发源于北京市昌平区及海淀区一带燕山以南，有39条支流分别汇流为北沙河、东沙河和南沙河，在昌平区沙河镇汇合后称温榆河，沿途流经顺义区、朝阳区、通州区，依次汇入蔺沟、清河、坝河、凉水河等支流（其他支流有通惠河、凤港减河、龙凤河），流过通州区北关之后称为北运河。2015年6月13日，通州区五河交汇处被确立为京杭大运河北起点。然后流经河北省香河县、天津市武清区、在天津市大红桥汇入海河。全长142.7公里，流域面积6166平方公里。漕运咽喉河西务，曾盛极一时。</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">大清河，中国海河流域支流之一，一称上西河，因相邻的永定河、滹沱河两河均为多沙河流，而居中的大清河，河水清澈，得名大清河。</span></p><p><span style=\" font-size:14pt; font-weight:600;\">大清河系主要由南、北两支组成。凡流入西淀（白洋淀）的支流为南支，洪水在西淀蓄滞后由赵王河、枣林庄新道及赵王新河入大清河；流入东淀的支流为北支，北支主要为拒马河，在张坊又分成南、北拒马河，北拒马河纳小清河、琉璃河（大石河）后在东茨村以下称白沟河，南拒马河纳北易水、中易水后东流，在白沟镇与白沟河会合后叫大清河。  </span></p><p><span style=\" font-size:14pt; font-weight:600;\">南支自源头（唐河源头山西省浑源县南部的翠屏山  ）至枣林庄枢纽长336公里；北支自源头（拒马河源头河北省涞源县西北涞山）至新盖房枢纽长303公里。南支稍长，故原以南支的源头为大清河的源头，现代地理一般以拒马河南支与北支白沟河汇合点为大清河干流起点，所以拒马河源头就作为大清河源头。</span></p><p><span style=\" font-size:14pt; font-weight:600;\">大清河流经东淀第六堡与子牙河汇流称西河。少量洪水经西河通过西河闸枢纽入海河干流从海河闸枢纽入渤海，大量洪水通过进洪闸入独流减河经工农兵闸入渤海。河源至独流减河入海口工农兵闸（独流减河防潮闸）长483公里，流域面积43060平方公里（《河北省志·地理志》记为32700平方公里 </span></p><p><span style=\" font-size:14pt; font-weight:600;\">历史上，大清河中下游洪涝灾害频繁，随着中华人民共和国成立的多年治理及气候变化导致的流量缩减，大清河成为保定、东淀农业区的主要灌溉水源。也是白洋淀补水的重要来源。1960年代以前，大清河是保定地区至天津的主要航道，航运价值很高</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">子牙河，海河支流，又名盐河、沿河，位于大清河与漳卫南运河之间，由滹沱河和滏阳河两大支流及滏阳新河、子牙新河两条分洪河道组成，在献县藏家桥（1967年子牙新河开挖后新、老子牙河均以献县枢纽为起点）汇合后称子牙河。子牙河水系流经山西东北部、河北省南部，干流流经河北省献县、河间、大城等县市至天津市静海区第六堡与大清河汇流后称西河，在天津市金刚桥上游三岔河口（原在大红桥）与北运河汇合，以下河道为海河。</span></p><p><span style=\" font-size:14pt; font-weight:600;\">由河源（滹沱河河源泰戏山）至大红桥全长769公里，流域地跨山西、河北两省和天津市，流域面积46868平方公里；流域多年平均年径流量40.41亿立方米。</span></p><p><span style=\" font-size:14pt; font-weight:600;\">子牙河水系在历史上就上大下小，峰高、量大、流急的滹、滏二水，汇入子牙河后宣泄不及，便决口泛滥。中华人民共和国成立后，在滏阳河上游山区建临城、东武仕、朱庄3座大型水库。滹沱河上游山区建岗南、黄壁庄两座大型水库。下游开辟了滏阳新河、子牙新河，从献县分洪入海。子牙新河开挖以后，子牙河的主要任务是航运、排沥、灌溉以及相机宣泄洪水。</span></p><p><span style=\" font-size:14pt; font-weight:600;\">2021年6月29日上午10点，河北省大城县泊庄闸开启，子牙河水进入天津界，与子牙河天津境内有水河段汇合，顺利实现子牙河全线贯通。</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">南运河，中国隋唐南北大运河和元代京杭大运河的重要组成部分，隋、唐称永济渠，宋、元称御河，明、清称卫河，南接卫运河、鲁运河，原以山东临清为南起点，天津市海河三岔河口为北终点，与北运河相接。全长436公里。  1950年代年扩建四女寺枢纽，开挖独流减河，把南运河截断后， 南运河南起于四女寺节制闸，东北流经山东省德州市，河北省衡水、沧州地区，至静海区十一堡与子牙河汇合止，全长309公里（以下被独流减河截断）。至天津市金刚桥（三岔河口）为止，全长349公里。</span></p><p><span style=\" font-size:14pt; font-weight:600;\">现代水利上，南运河划分为海河流域漳卫南运河水系的最下端干流，是海河水系中最长的一条河，主要由漳河及卫河两大支流组成。以漳河中的浊漳河南源为源，流经山西、河北、河南、山东、天津五省、市，至天津市金钢桥（三岔河口）附近注入海河。据《海河志》《天津通志》全长959公里，流域面积37584平方公里。 ；据2003版《漳卫南运河志》全长为972.3公里。 据2013版《漳卫南运河志》则为1050公里，流域面积37700平方公里。</span></p><p><span style=\" font-size:14pt; font-weight:600;\">南运河自隋代开凿至明清，始终是国家的交通命脉，明、清两代每年都有约400万石漕粮经沧州运至北京。此外，还有大量瓷器、盐、煤等货物靠运河水路运输。漕运的繁忙和南北物资的融汇给沿河德州、沧州、吴桥、泊头、天津等城市带来了两岸经济的繁荣，更有了大小不等的码头、摆渡。</span></p><p><span style=\" font-size:14pt; font-weight:600;\">1978年，由于缺乏水源，南运河航运全线中断。成为海河流域南部的排水河道及引水通道。引黄入津、引岳入津都是通过此河道。</span></p></body></html>"))
